### PR TITLE
Fix issue #9 on statuscake_ssl_valid_util_sec metrics

### PR DESCRIPTION
**Pull request by sadmin91**
Correct issue #9

### CODE REVIEW

**Review by mtulio — APPROVED** [review]

**Comment by mtulio** [comment]
Great, thanks @sadmin91

**Comment by sadmin91** [comment]
Hello,
Could you merge this PR and create a new release (0.3.1, I suppose)?
Thanks.

**Comment by mtulio** [comment]
done https://github.com/mtulio/statuscake-exporter/releases/tag/v0.3.1

**Comment by mtulio** [comment]
Fix #9

**Pull request merged**
